# Generated by Django 6.0.7 on 2026-08-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('blood_group', models.CharField(max_length=5)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
    ]
