# Generated by Django 6.1 on 2026-08-31 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.PositiveIntegerField()),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('token_no', models.PositiveIntegerField(blank=True, null=True)),
                ('appointment_type', models.CharField(choices=[('WALK_IN', 'Walk-in'), ('PRIOR_BOOKING', 'Prior Booking')], max_length=20)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('CONSULTED', 'Consulted'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
        ),
    ]
