# Generated by Django 6.1 on 2026-09-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labbill',
            name='bill_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
