# Generated by Django 6.1 on 2026-09-03 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labprescription',
            name='test_name',
        ),
        migrations.AddField(
            model_name='labprescription',
            name='lab_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_prescriptions', to='admin_panel.labtest'),
        ),
    ]
